"""initial schema

Revision ID: 6e886c7a3826
Revises: 
Create Date: 2026-05-13 14:33:54.752829

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '6e886c7a3826'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('cities',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('slug', sa.String(length=100), nullable=False),
    sa.Column('region', sa.String(length=100), nullable=False),
    sa.Column('sort_order', sa.Integer(), nullable=False),
    sa.Column('playlist_id', sa.String(length=100), nullable=True),
    sa.Column('cultural_profile', sa.Text(), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name'),
    sa.UniqueConstraint('slug')
    )
    op.create_table('generation_history',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('city_id', sa.Integer(), nullable=False),
    sa.Column('used_themes', sa.Text(), nullable=False),
    sa.Column('used_titles', sa.Text(), nullable=False),
    sa.Column('used_hooks', sa.Text(), nullable=False),
    sa.Column('used_keywords', sa.Text(), nullable=False),
    sa.Column('used_instruments', sa.Text(), nullable=False),
    sa.Column('used_moods', sa.Text(), nullable=False),
    sa.Column('used_tempos', sa.Text(), nullable=False),
    sa.Column('used_style_prompts', sa.Text(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['city_id'], ['cities.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('city_id')
    )
    op.create_table('songs',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('city_id', sa.Integer(), nullable=False),
    sa.Column('title', sa.String(length=300), nullable=True),
    sa.Column('theme', sa.String(length=100), nullable=True),
    sa.Column('mood', sa.String(length=200), nullable=True),
    sa.Column('tempo', sa.String(length=100), nullable=True),
    sa.Column('vocal_type', sa.String(length=100), nullable=True),
    sa.Column('style_variant', sa.String(length=100), nullable=True),
    sa.Column('concept', sa.Text(), nullable=True),
    sa.Column('lyrics', sa.Text(), nullable=True),
    sa.Column('lyric_attempt', sa.Integer(), nullable=False),
    sa.Column('quality_score', sa.Float(), nullable=True),
    sa.Column('quality_report', sa.Text(), nullable=True),
    sa.Column('rejected_reason', sa.Text(), nullable=True),
    sa.Column('suno_task_id', sa.String(length=100), nullable=True),
    sa.Column('suno_style_prompt', sa.Text(), nullable=True),
    sa.Column('suno_full_prompt', sa.Text(), nullable=True),
    sa.Column('suno_lyrics', sa.Text(), nullable=True),
    sa.Column('image_prompt', sa.Text(), nullable=True),
    sa.Column('youtube_metadata', sa.Text(), nullable=True),
    sa.Column('youtube_video_id', sa.String(length=50), nullable=True),
    sa.Column('youtube_short_id', sa.String(length=50), nullable=True),
    sa.Column('youtube_long_video_id', sa.String(length=50), nullable=True),
    sa.Column('youtube_short_video_id', sa.String(length=50), nullable=True),
    sa.Column('audio_path', sa.String(length=500), nullable=True),
    sa.Column('video_path', sa.String(length=500), nullable=True),
    sa.Column('short_path', sa.String(length=500), nullable=True),
    sa.Column('thumbnail_path', sa.String(length=500), nullable=True),
    sa.Column('background_path', sa.String(length=500), nullable=True),
    sa.Column('long_video_path', sa.String(length=500), nullable=True),
    sa.Column('short_video_path', sa.String(length=500), nullable=True),
    sa.Column('background_image_path', sa.String(length=500), nullable=True),
    sa.Column('subtitles_path', sa.String(length=500), nullable=True),
    sa.Column('status', sa.String(length=50), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('uploaded_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['city_id'], ['cities.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('quality_reports',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('song_id', sa.Integer(), nullable=False),
    sa.Column('score', sa.Float(), nullable=False),
    sa.Column('issues', sa.Text(), nullable=False),
    sa.Column('rejected_reason', sa.Text(), nullable=True),
    sa.Column('reviewer_model', sa.String(length=100), nullable=False),
    sa.Column('attempt_number', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['song_id'], ['songs.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('run_logs',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('run_id', sa.String(length=100), nullable=False),
    sa.Column('city_id', sa.Integer(), nullable=True),
    sa.Column('song_id', sa.Integer(), nullable=True),
    sa.Column('stage', sa.String(length=100), nullable=False),
    sa.Column('status', sa.String(length=50), nullable=False),
    sa.Column('message', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['city_id'], ['cities.id'], ),
    sa.ForeignKeyConstraint(['song_id'], ['songs.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('youtube_quota_logs',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('date', sa.String(length=10), nullable=False),
    sa.Column('operation', sa.String(length=100), nullable=False),
    sa.Column('cost', sa.Integer(), nullable=False),
    sa.Column('song_id', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['song_id'], ['songs.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('youtube_quota_logs')
    op.drop_table('run_logs')
    op.drop_table('quality_reports')
    op.drop_table('songs')
    op.drop_table('generation_history')
    op.drop_table('cities')
    # ### end Alembic commands ###
